(module
(memory 1)
(global $_p (mut i32) (i32.const 0))
(table 1 funcref)
(elem (i32.const 0) $_f0)
(type $_t3 (func (param i32) (param i32) (param i32) (result i32)))
(export "_start" (func $_start))
(func $_start  (result i32) 
  (i32.const 0)
)
(func $_f0 (param $_nv i32) (param $x i32) (param $_k1 i32) (result i32) (local $__k1 i32)
  (local.set $_nv (i32.load offset=4 (local.get $_nv)))
  (local.set $_nv (global.get $_p))
  (global.set $_p (i32.add (global.get $_p) (i32.const 8)))
  (i32.store offset=0 (local.get $_nv) (local.get $x))
  (i32.store offset=4 (local.get $_nv) (local.get $_k1))
  (local.set $__k1 (i32.load offset=0 (local.get $_k1)))
  (call_indirect (type $_t2) (local.get $_k1) (local.get $x) (local.get $__k1))
)
)